Update git submodules
* Update castellan from branch 'master'
  to 7f48310ccd0fbe73c6e3b56c415c010126549964
  - Merge "Use more explicit import"
  - Use more explicit import
    
    This is not seen as a problem now because import of urllib.parse is
    implicitly done by the requests library, but in general importing
    urllib does not automatically import urllib.parse .
    
    >>> import urllib
    >>> urllib.parse.urljoin('http://localhost', 'foo')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    AttributeError: module 'urllib' has no attribute 'parse'
    
    Make sure we explicitly import the required submodule to avoid
    problems caused by implicit compatibility code.
    
    Change-Id: I3be7e5136926d1ad40279ae626b0c683ba389705
    Signed-off-by: Takashi Kajinami <kajinamit@oss.nttdata.com>